version = "2.5.4"
license = "LGPL-2.0-or-later"
dependencies = ["m4"]
build_dependencies = []

[source]
url = "https://ftpmirror.gnu.org/gnu/libtool/libtool-2.5.4.tar.gz"
mirrors = [
  "https://ftp.gnu.org/gnu/libtool/libtool-2.5.4.tar.gz",
  "https://mirrors.kernel.org/gnu/libtool/libtool-2.5.4.tar.gz",
  "https://mirror.csclub.uwaterloo.ca/gnu/libtool/libtool-2.5.4.tar.gz"
]
checksum = "da8ebb2ce4dcf46b90098daf962cffa68f4b4f62ea60f798d0ef12929ede6adf"

[targets.linux]

[targets.mac]
build_script = "macos_build"
