version = "3.14.6"
license = "Python Software Foundation License Version 2" # Exception for documentation with dual license PSF License Version 2 and the Zero-Clause BSD license
dependencies = ["mpdecimal", "openssl@3.0.0-4.0.0", "sqlite", "xz", "zstd@>1.4.5"]
build_dependencies = []
external_test_files = ["test.py"]

[source]
url = "https://www.python.org/ftp/python/3.14.6/Python-3.14.6.tgz"
checksum = "74d0d71d0600e477651a077101d6e62d1e2e69b8e992ba18c993dd643b7ba222"
size = 31234628

[targets.unix]

[targets.windows]
