version = "3.5.0"
license = "GPL-2.0-or-later"
dependencies = ["ncurses@>6.0"]
build_dependencies = ["autoconf", "automake", "libtool"]

[source]
url = "https://github.com/htop-dev/htop/archive/refs/tags/3.5.0.tar.gz"
checksum = "cf0e72abf670ff3547d9130e129d2a97a657a5b20c74132c17502c817babbb41"
size = 469060

[targets.unix]
