version = "6.6"
dependencies = []
build_dependencies = []

[source]
url = "https://ftpmirror.gnu.org/gnu/ncurses/ncurses-6.6.tar.gz" 
mirrors = [
  "https://invisible-island.net/archives/ncurses/ncurses-6.6.tar.gz",
  "https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.6.tar.gz",
  "https://mirrors.kernel.org/gnu/ncurses/ncurses-6.6.tar.gz",
  "https://invisible-mirror.net/archives/ncurses/ncurses-6.6.tar.gz"
]
checksum = "355b4cbbed880b0381a04c46617b7656e362585d52e9cf84a67e2009b749ff11"

[targets.linux]

[targets.mac]
skip_symlinking = true
