version = "3.6.2"
license = "Apache-2.0"
dependencies = ["ca-certificates"]
build_dependencies = []

[source]
url = "https://github.com/openssl/openssl/releases/download/openssl-3.6.2/openssl-3.6.2.tar.gz"
checksum = "aaf51a1fe064384f811daeaeb4ec4dce7340ec8bd893027eee676af31e83a04f"

[targets.linux]
build_dependencies = ["perl"]

[targets.mac]

[targets.windows]
build_dependencies = ["perl"]
