supported_packages = [
    "autoconf",
    "automake",
    "bzip2",
    "ca-certificates",
    "calc",
    "cmake",
    "htop",
    "libedit",
    "libffi",
    "libgit2",
    "libpng",
    "libssh2",
    "libtool",
    "llhttp",
    "lz4",
    "m4",
    "make",
    "mpdecimal",
    "nasm",
    "ncurses",
    "openssl",
    "packit",
    "pcre2",
    "perl",
    "pkgconf",
    "readline",
    "scdoc",
    "sqlite",
    "tree",
    "xz",
    "zlib",
    "zlib-ng",
    "zlib-ng-compat",
    "zstd"
]
