supported_packages = [
    "autoconf",
    "automake",
    "bzip2",
    "ca-certificates",
    "calc",
    "cmake",
    "htop",
    "libssh2",
    "libtool",
    "llhttp",
    "lz4",
    "m4",
    "make",
    "nasm",
    "ncurses",
    "openssl",
    "packit",
    "perl",
    "pkgconf",
    "readline",
    "sqlite",
    "tree",
    "xz",
    "zlib",
    "zlib-ng",
    "zlib-ng-compat",
]
