#!/bin/sh
cd calc-$PACKIT_PACKAGE_VERSION

make PREFIX="$PACKIT_PACKAGE_PATH" BINDIR="$PACKIT_PACKAGE_PATH/bin" LIBDIR="$PACKIT_PACKAGE_PATH/lib" MANDIR="$PACKIT_PACKAGE_PATH/share/man" CALC_INCDIR="$PACKIT_PACKAGE_PATH/include/calc" CALC_SHAREDIR="$PACKIT_PACKAGE_PATH/share" USE_READLINE="-DUSE_READLINE" READLINE_LIB="-lreadline" READLINE_EXTRAS="-lcurses"

make install PREFIX="$PACKIT_PACKAGE_PATH"
