version = "1.11.1"
license = "BSD-3-Clause"
dependencies = ["openssl"]
build_dependencies = []
external_test_files = ["test.c"]

[source]
url = "https://libssh2.org/download/libssh2-1.11.1.tar.gz"
mirrors = [
    "https://github.com/libssh2/libssh2/releases/download/libssh2-1.11.1/libssh2-1.11.1.tar.gz",
]
checksum = "d9ec76cbe34db98eec3539fe2c899d26b0c837cb3eb466a56b0f109cabf658f7"
size = 1093012

[targets.mac]

[targets.linux]
dependencies = ["zlib-ng-compat"]

[targets.windows]
build_dependencies = ["cmake@>=3.18"]
