cd sqlite-autoconf-%PACKIT_ARGS_ARCHIVE_VERSION%

REM Call vcvarsall.bat to initialize MSVC build environment
call "%PACKIT_VCVARSALL%" %PACKIT_VCVARSALL_ARCH%

set "OPTIONS="
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_API_ARMOR=1"
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_COLUMN_METADATA=1"
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_DBSTAT_VTAB=1"
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_FTS3_PARENTHESIS=1"
set "OPTIONS=%OPTIONS% /DSQLITE_SECURE_DELETE=1"
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_STMTVTAB=1"
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_STAT4=1"
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_UNLOCK_NOTIFY=1"
set "OPTIONS=%OPTIONS% /DSQLITE_MAX_VARIABLE_NUMBER=250000"
set "OPTIONS=%OPTIONS% /DSQLITE_USE_URI=1"
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_MATH_FUNCTIONS=1"
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_FTS3=1"
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_FTS4=1"
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_FTS5"
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_GEOPOLY=1"
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_RTREE=1"
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_SESSION=1"
set "OPTIONS=%OPTIONS% /DSQLITE_ENABLE_PREUPDATE_HOOK=1"

nmake -f Makefile.msc USE_ZLIB=1 BUILD_ZLIB=0 ZLIBDIR="%PACKIT_PACKAGE_DEPENDENCIES_PATH%\zlib-ng-compat" OPTIONS="%OPTIONS%"
if ERRORLEVEL 1 (
    echo Building sqlite failed
    exit /b 1
)

mkdir "%PACKIT_PACKAGE_PATH%\bin\"
mkdir "%PACKIT_PACKAGE_PATH%\lib\"
mkdir "%PACKIT_PACKAGE_PATH%\include\"

move "sqlite3.exe" "%PACKIT_PACKAGE_PATH%\bin\"
move "sqlite3.dll" "%PACKIT_PACKAGE_PATH%\bin\"
move "sqlite3.lib" "%PACKIT_PACKAGE_PATH%\lib\"
move "sqlite3.h" "%PACKIT_PACKAGE_PATH%\include\"
