version = "5.42.2"
license = { any = ["Artistic-1.0-Perl", "GPL-1.0-or-later"] }
dependencies = []
build_dependencies = []

[script_args]
lib_version = "5.42"

[source]
url = "https://www.cpan.org/src/5.0/perl-5.42.2.tar.gz"
checksum = "9384e8deb75b7b1695e5637971b752281aaecd025a3d5d4734d33c1d0adfee47"

[targets.unix]

[targets.windows]
