cmake -S build/cmake -B build -DCMAKE_INSTALL_PREFIX="%PACKIT_PACKAGE_PATH%" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DZSTD_PROGRAMS_LINK_SHARED=ON -DZSTD_LEGACY_SUPPORT=ON -DZSTD_ZLIB_SUPPORT=ON -DZSTD_LZMA_SUPPORT=ON -DZSTD_LZ4_SUPPORT=ON -DCMAKE_CXX_STANDARD=11 -DZLIB_LIBRARY="%PACKIT_PACKAGE_DEPENDENCIES_PATH%\zlib-ng-compat\lib\zlib.lib" -DZLIB_INCLUDE_DIR="%PACKIT_PACKAGE_DEPENDENCIES_PATH%\zlib-ng-compat\include" -DLIBLZMA_INCLUDE_DIR="%PACKIT_PACKAGE_DEPENDENCIES_PATH%\xz\include" -DLIBLZMA_LIBRARY="%PACKIT_PACKAGE_DEPENDENCIES_PATH%\xz\lib\lzma.lib" -DLIBLZ4_INCLUDE_DIR="%PACKIT_PACKAGE_DEPENDENCIES_PATH%\lz4\include" -DLIBLZ4_LIBRARY="%PACKIT_PACKAGE_DEPENDENCIES_PATH%\lz4\lib\lz4.lib"
if ERRORLEVEL 1 exit /b %ERRORLEVEL%

cmake --build build --config Release
if ERRORLEVEL 1 exit /b %ERRORLEVEL%

ctest -C Release
if ERRORLEVEL 1 exit /b %ERRORLEVEL%

cmake --install build --config Release
if ERRORLEVEL 1 exit /b %ERRORLEVEL%
