version = "0.19"
license = "MIT"
dependencies = []
build_dependencies = ["cmake"]
external_test_files = ["test.c"]

[source]
url = "https://github.com/json-c/json-c/releases/download/json-c-0.19-20260627/json-c-0.19.tar.gz"
checksum = "37ad0249902e301bd9052bf712e511fcc6acff4ecaad4b5900aad9ce564e26de"
size = 462232

[targets.unix]

[targets.windows]
