version = "1.3.2"
license = "Zlib"
dependencies = []
build_dependencies = []
external_test_files = ["test.c"]

[source]
url = "https://zlib.net/zlib-1.3.2.tar.gz"
mirrors = [
    "https://github.com/madler/zlib/releases/download/v1.3.2/zlib-1.3.2.tar.gz"
]
checksum = "bb329a0a2cd0274d05519d61c667c062e06990d72e125ee2dfa8de64f0119d16"
size = 1502830

[targets.windows]

[targets.unix]
