version = "1.53.0"
license = "MIT"
dependencies = []
build_dependencies = []
external_test_files = ["test.c"]

[source]
url = "https://dist.libuv.org/dist/v1.53.0/libuv-v1.53.0.tar.gz"
checksum = "cb0d6dd2128d5a95bd242c6cc982a24fe608fa93da57b6b4ec763b0018c53e64"
size = 1391596

[targets.mac]
build_dependencies = ["autoconf", "automake", "libtool"]

[targets.linux]
build_dependencies = ["autoconf", "automake", "libtool", "m4"]

[targets.windows]
build_dependencies = ["cmake"]
test_requirements = ["msvc"]
