#!/bin/sh
cd tree-$PACKIT_PACKAGE_VERSION

make PREFIX="$PACKIT_PACKAGE_PATH" MANDIR="$PACKIT_PACKAGE_PATH/share/man"

make install PREFIX="$PACKIT_PACKAGE_PATH" MANDIR="$PACKIT_PACKAGE_PATH/share/man"
