version = "1.4.20"
license = "GPL-3.0-only"
dependencies = []
build_dependencies = []

[source]
url = "https://ftpmirror.gnu.org/gnu/m4/m4-1.4.20.tar.gz"
mirrors = [
  "https://ftp.gnu.org/gnu/m4/m4-1.4.20.tar.gz",
  "https://mirrors.kernel.org/gnu/m4/m4-1.4.20.tar.gz",
  "https://mirror.csclub.uwaterloo.ca/gnu/m4/m4-1.4.20.tar.gz"
]
checksum = "6ac4fc31ce440debe63987c2ebbf9d7b6634e67a7c3279257dc7361de8bdb3ef"

[targets.unix]
