version = "4.0.1"
license = "BSD-2-Clause"
dependencies = []
build_dependencies = []
external_test_files = ["test.c"]

[source]
url = "https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-4.0.1.tar.gz"
checksum = "96d33abb4bb0070c7be0fed4246cd38416188325f820468214471938545b1ac8"
size = 316268

[targets.unix]

[targets.windows]
build_dependencies = ["cmake"]
build_requirements = ["msvc"]
test_requirements = ["msvc"]
