version = "4.4"
license = "GPLv3+"
dependencies = []
build_dependencies = []

[source]
url = "https://ftpmirror.gnu.org/gnu/make/make-4.4.tar.gz"
mirrors = [
  "https://ftp.gnu.org/gnu/make/make-4.4.tar.gz"
]
checksum = "8814ba072182b605d156d7589c19a43b89fc58ea479b9355146160946f8cf6e9"

[targets.unix]

[targets.windows]
