version = "3.53.2"
license = "blessing"
dependencies = ["zlib-ng-compat"]
build_dependencies = []
#TODO: could use TCL for running make test

[source]
url = "https://sqlite.org/2026/sqlite-autoconf-3530200.tar.gz"
checksum = "588ad51949419a56ebe81fe56193d510c559eb94c9a57748387860b5d3069316"

[targets.linux]
dependencies = ["readline"]

[targets.mac]
dependencies = ["readline"]
skip_symlinking = true

[targets.windows]
