version = "6.1.0"
license = "BSL-1.0"
dependencies = []
build_dependencies = ["cmake"]

[source]
url = "https://github.com/msgopack/msgpack-c/archive/refs/tags/c-6.1.0.tar.gz"
checksum = ""

[targets.unix]

[targets.windows]