version = "3.4.1"
license = "GPL-2.0-or-later"
dependencies = ["ncurses@>6.0"]
build_dependencies = ["autoconf", "automake", "libtool"]

[source]
url = "https://github.com/htop-dev/htop/archive/refs/tags/3.4.1.tar.gz"
mirrors = [
  "https://codeload.github.com/htop-dev/htop/tar.gz/refs/tags/3.4.1"
]
checksum = "af9ec878f831b7c27d33e775c668ec79d569aa781861c995a0fbadc1bdb666cf"

[targets.unix]
