version    = "3.4.1"
dependencies = ["ncurses"] # TODO: should be ncurses@>=6.0
build_dependencies = ["autoconf", "automake"] # TODO: maybe also needs libtool as build dependency

# Linux aarch64 (ARM64)
[targets.aarch64-unknown-linux-gnu]
url       = "https://github.com/htop-dev/htop/archive/refs/tags/3.4.1.tar.gz"

# macOS Intel
[targets.x86_64-apple-darwin]
url       = "https://github.com/htop-dev/htop/archive/refs/tags/3.4.1.tar.gz"

# macOS ARM (Apple Silicon)
[targets.aarch64-apple-darwin]
url       = "https://github.com/htop-dev/htop/archive/refs/tags/3.4.1.tar.gz"
