#!/bin/sh

make PREFIX="$PACKIT_PACKAGE_PATH" -j $PACKIT_BUILD_JOBS_COUNT

[ "${PACKIT_EXECUTE_BUILD_TEST:-}" = "1" ] && make check PREFIX="$PACKIT_PACKAGE_PATH" -j $PACKIT_BUILD_JOBS_COUNT

make install PREFIX="$PACKIT_PACKAGE_PATH"
