#!/bin/sh

# Removing the `Generated by scdoc` line is required to ensure the script works for each version of scdoc
scdoc < test.scd | sed '/^\.\\" Generated by scdoc/d' > test.output

if cmp -s "test.output" "test.expected"; then
    exit 0
fi

exit 1
