#!/bin/sh

# Removing the `Generated by scdoc` line is required to ensure the script works for each version of scdoc
SOURCE_DATE_EPOCH=0 scdoc < test.scd | sed '/^\.\\" Generated by scdoc/d' > test.output

if ! cmp -s "test.output" "test.expected"; then
    echo "Test failed: test output does not match the expected output"
    exit 1
fi
