version = "2.16.1.2"
license = "LGPL-2.1-or-later"
dependencies = ["readline"]
build_dependencies = []

[source]
url = "https://github.com/lcn2/calc/archive/refs/tags/v2.16.1.2.tar.gz"
checksum = "cb5b0576c3d206ed55b6929cc3a1ebc5afedbfdc70d528274cbac8e650c56d77"

[targets.unix]
