version = "4.0.1"
license = "Apache-2.0"
dependencies = ["ca-certificates"]
build_dependencies = []
external_test_files = ["test.pem"]

[source]
url = "https://github.com/openssl/openssl/releases/download/openssl-4.0.1/openssl-4.0.1.tar.gz"
checksum = "2db3f3a0d6ea4b59e1f094ace2c8cd536dffb87cdc39084c5afa1e6f7f37dd09"
size = 55079428

[targets.linux]
build_dependencies = ["perl"]

[targets.mac]

[targets.windows]
build_dependencies = ["perl"]

[targets.x86_64-pc-windows-msvc]
build_dependencies = ["perl", "nasm"]
