[package]
version    = "6.5"
dependencies = []
 
# Linux aarch64 (ARM64)
[[targets.aarch64-unknown-linux-gnu]]
url       = "https://invisible-mirror.net/archives/ncurses/ncurses-6.5.tar.gz"
installer_type = "unpack"

# macOS Intel
[[targets.x86_64-apple-darwin]]
url       = "https://invisible-mirror.net/archives/ncurses/ncurses-6.5.tar.gz"
installer_type = "unpack"

# macOS ARM (Apple Silicon)
[[targets.aarch64-apple-darwin]]
url       = "https://invisible-mirror.net/archives/ncurses/ncurses-6.5.tar.gz"
installer_type = "unpack"

