version = "3.5.1"
license = "GPL-2.0-or-later"
dependencies = ["ncurses@>6.0"]
build_dependencies = ["autoconf", "automake", "libtool"]

[source]
url = "https://github.com/htop-dev/htop/archive/refs/tags/3.5.1.tar.gz"
checksum = "dfc4a09845e9bc86f466a722e62b8f87d59028ff39689077ff2257a6a605061d"

[targets.unix]
