version = "1.51.0"
license = { all = "MIT", "BSD-3-Clause", "ISC" }
dependencies = []
build_dependencies = ["cmake"]

[source]
url = "https://dist.libuv.org/dist/v1.51.0/libuv-v1.51.0.tar.gz"
checksum = "7be14604eadc348db9e58db58ba7576624b9dc5cab93946211c9c6bb3f8fc39e"

[targets.unix]

[targets.windows]
